import * as COL from "./collection.js?v=0.44.0";
export const WEEKS=22,EXTENSION_WEEKS=2,EXTENSION_DISCOUNT=.25;
// A recurring fictional sponsor. Amounts use the engine's thousands-of-dollars unit.
export function ensure(s){s.marsTravel??={version:1,wins:0,strikes:0,nextOffer:0,deal:null,history:[],last:'Elena Vale wants audiences to imagine a life beyond Earth.'};}
export function offer(s){const c=s.marsTravel;return !!c&&(!s.collection||COL.owns(s,'genre','Sci-fi')&&COL.owns(s,'setting','Frontier'))&&!c.deal&&c.strikes<2&&s.week>=c.nextOffer&&s.week+WEEKS<260;}
export function eligible(m){return m?.genre==='Sci-fi'&&['development','packaging'].includes(m.stage);}
export function accept(s){ensure(s);const c=s.marsTravel;if(!offer(s))throw Error('Mars Travel has no commission available right now.');c.deal={accepted:s.week,due:s.week+WEEKS,payment:Math.min(1000,600+c.wins*200),movie:null,extended:false};c.last='“A colony on screen. A future people can picture. Deliver on time and we will pay.”';}
export function bind(s,m){const d=s.marsTravel?.deal;if(!d||!eligible(m))throw Error('Choose an unreleased sci-fi film still in development or packaging.');if(d.movie)throw Error('A film is already attached to this commission.');d.movie=m.id;}
export function extend(s){const d=s.marsTravel?.deal;if(!d||d.extended||s.week>d.due-2||d.due+EXTENSION_WEEKS>=260)throw Error('An extension must be requested at least two weeks before the deadline, once, within the studio run.');d.due+=EXTENSION_WEEKS;d.payment*=1-EXTENSION_DISCOUNT;d.extended=true;s.marsTravel.last='“Thank you for telling me early. Two more weeks—but the fee is 25% lower.”';}
function close(s,ok,reason,m){const c=s.marsTravel,d=c.deal;if(!d)return;if(ok){s.cash+=d.payment;m.receipts+=d.payment;m.sponsorIncome=(m.sponsorIncome??0)+d.payment;c.wins++;c.nextOffer=s.week+12;c.last=`“${m.title} delivered what we agreed. Let’s talk again.”`;}else{c.strikes++;c.nextOffer=s.week+52;c.last=c.strikes>=2?'“Two missed commitments. We won’t commission another film from this studio.”':'“We were counting on this launch. We need time before discussing another commission.”';}c.history.push({week:s.week,movie:d.movie,title:m?.title??'Unassigned commission',outcome:ok?'delivered':'missed',payment:ok?d.payment:0,reason});c.deal=null;}
export function deliver(s,m,notify){const d=s.marsTravel?.deal;if(!d||d.movie!==m.id||m.stage!=='theaters'||m.release==null||s.week<m.release)return;const ok=s.week<=d.due&&m.genre==='Sci-fi'&&(m.movieCards?COL.has(m,'setting','Frontier'):m.scifiCards?.setting.includes('Colony'));const payment=d.payment;close(s,ok,ok?'Released on time with the requested setting.':'The released film did not meet the agreed cards or deadline.',m);notify(ok?`Mars Travel paid $${Math.round(payment*1000).toLocaleString('en-US')} for ${m.title}.`:`Mars Travel: ${m.title} did not meet the commission.`);}
export function tick(s,notify){ensure(s);const d=s.marsTravel.deal;if(!d)return;const m=s.movies.find(m=>m.id===d.movie);if(s.week>d.due||m?.cancelled){close(s,false,m?.cancelled?'Attached movie was shelved.':'Release deadline missed.',m);notify('Mars Travel’s commission was not delivered. Elena remembers the missed commitment.');}}
export function decline(s){if(!offer(s))throw Error('No offer is waiting.');s.marsTravel.nextOffer=s.week+12;s.marsTravel.last='“Understood. Better to say no than promise a film you cannot deliver.”';}
