const hash=s=>[...s].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,13);
export const INCIDENTS=[
 {title:'The ending is not landing',text:'We have the footage, but the final scenes do not earn the payoff. More money will not solve the writing overnight.',options:[['wait','Give the rewrite room to breathe',2,0],['rework','Simplify the ending',1,2],['coverage','Keep the existing ending',0,6]]},
 {title:'The lead needs recovery time',text:'Our lead needs time off. We can rearrange some scenes, but we cannot ask them to work through it.',options:[['wait','Pause the shoot for recovery',3,0],['rework','Film around their absence',1,3],['coverage','Reduce the remaining lead scenes',1,5]]},
 {title:'The location is unavailable',text:'Access has fallen through. The original location needs time; a substitute will change how we stage the scene.',options:[['wait','Wait for the original location',3,0],['rework','Restage at another location',1,3],['coverage','Rewrite around existing sets',0,6]]},
 {title:'The effects sequence needs another pass',text:'The images are not convincing yet. The team needs time to rebuild the sequence, or we need a simpler version.',options:[['wait','Allow another effects pass',2,0],['rework','Simplify the sequence',1,2],['coverage','Use a less ambitious cut',0,5]]},
 {title:'Weather has stopped the exterior shoot',text:'We cannot safely film the planned exteriors. We can wait, move the scene indoors, or tell it differently.',options:[['wait','Wait for safe conditions',2,0],['rework','Restage the scene indoors',1,2],['coverage','Rewrite using existing footage',0,5]]},
];
INCIDENTS.push({title:'The crew is running on empty',text:'We have been stretching every day. Give us recovery time, or simplify the remaining scenes.',options:[['wait','Rest the crew · loyalty +6',2,0],['rework','Simplify the remaining shoot · loyalty +1',0,2]]});
export function start(m){m.delayPlan={version:1,count:0,remaining:0,elapsed:0,holdingPaid:0,history:[]};}
export function due(m){const d=m.delayPlan;return d&&d.count<(m.scale==='Blockbuster'?2:1)&&m.progress>=Math.max(2,Math.floor(m.duration*(d.count ? .7 : .35)))&&m.progress<m.duration;}
export function incident(m){const d=m.delayPlan;let index=(hash(m.id)+d.count)%5;if(index===3&&!['Sci-fi','Action'].includes(m.genre))index=0;d.count++;return {kind:'delay',index,title:INCIDENTS[index].title,text:INCIDENTS[index].text};}
export function plan(s,m,choice){if(m.event?.kind!=='delay')throw Error('No schedule decision is waiting.');const opt=INCIDENTS[m.event.index].options.find(x=>x[0]===choice);if(!opt)throw Error('Choose a production response.');const remaining=m.duration-m.progress;let resume=s.week+opt[2];const people=[...m.contracts,m.director].map(c=>s.people.find(p=>p.id===c.id));const bookings=people.flatMap(p=>p.bookings.filter(b=>b.movie!==m.id&&b.end>s.week));let conflict;do{conflict=bookings.find(b=>resume<b.end&&resume+remaining>b.start);if(conflict)resume=conflict.end;}while(conflict);return {choice,label:opt[1],weeks:resume-s.week,baseWeeks:opt[2],conflictWeeks:resume-s.week-opt[2],damage:opt[3],resume,wrap:resume+remaining,holdingPerWeek:m.weekly*.1};}
export function resolve(s,m,choice){const p=plan(s,m,choice),d=m.delayPlan;d.remaining=p.weeks;m.penalty+=p.damage;for(const c of [...m.contracts,m.director]){const person=s.people.find(x=>x.id===c.id);person.bookings=person.bookings.flatMap(b=>b.movie!==m.id?[b]:b.start<s.week?[{...b,end:Math.min(b.end,s.week)}]:[]);person.bookings.push({start:p.resume,end:p.wrap,movie:m.id});}
 const outcome=`${m.event.title}: ${p.label}. ${p.weeks} extra week(s), ${p.damage} quality penalty${p.conflictWeeks?`; includes ${p.conflictWeeks} week(s) waiting for cast/director bookings`:''}.`;
 d.history.push({week:s.week,...p,title:m.event.title,outcome});m.productionDecisions.push({week:s.week,kind:'delay',outcome});m.event=null;return outcome;}
export function pauseCost(m){return m.delayPlan?.remaining>0?m.weekly*.1:m.weekly;}
