// Authored genre content. Story tags are local to each pack.
const option=(id,label,detail,tags=[])=>({id,label,detail,tags});
const character=(id,name,title,options)=>({id,name,title,options});
const c=(id,title,text,needs=[],add=[],demand=0)=>({id,title,text,needs,add,effects:demand});
const steps=['Setup','Complication','Response','Resolution','Cost','Aftermath'];
export const GENRE_PACKS=[{
 id:'wedding-crash-course',title:'Wedding Crash Course',genre:'Comedy',subgenre:'Slapstick',scale:'Small',quality:70,difficulty:55,price:95,
 headline:'Two weddings. One ballroom.',tagline:'EVERY LIE NEEDS A PLUS ONE',theme:'comedy',department:'crew',departmentLabel:'Crew & post-production',
 premise:'Nora double-books a struggling hotel for the wedding of the year. Keeping both parties happy means confronting the hotel owner, an escalating lie, and her own need to look in control.',
 steps,questions:['What starts the wedding chaos?','What makes the cover-up impossible?','How does Nora handle the mess?','What becomes the big comic payoff?','What does saving the day cost?','Who gets the last laugh?'],
 characters:[
 character('hero','Nora Bell','Protagonist',[
 option('planner','Perfectionist planner','Needs everyone to believe she has it handled.',['control']),
 option('impostor','Accidental celebrity','Mistaken for an elite wedding fixer.',['disguise']),
 option('rookie','Rookie event manager','Has one chance to save the family business.',['family'])]),
 character('villain','Victor Lane','Opposition · hotel owner',[
 option('owner','Status-obsessed owner','Wants a flawless showcase for wealthy guests.',['status']),
 option('brother','Competitive older brother','Thinks Nora cannot run an event without him.',['family','personal']),
 option('sponsor','Controlling sponsor','Will fund the hotel if the wedding follows his brand.',['sponsor'])]),
 character('ally','Jules Park','Supporting · partner in chaos',[
 option('chef','Chef / best friend','Can turn a kitchen disaster into a feast.',['food']),
 option('comic','Comic / former roommate','Reads a room better than Nora does.',['improv']),
 option('magician','Magician / ex-partner','Knows how to distract an entire ballroom.',['illusion'])]),
 character('anchor','Sam Rivera','Supporting · emotional anchor',[
 option('sibling','Sibling / wedding singer','Wants Nora to stop managing everyone’s feelings.',['music','family']),
 option('reporter','Reporter / old crush','Is covering the wedding, and knows the real Nora.',['media']),
 option('friend','Friend / union steward','Knows every worker keeping the hotel running.',['workers'])])],
 original:{characters:['planner','owner','chef','sibling'],beats:['double','mic','confess','toast','deposit','apology']},
 labels:{clash:'two competing wedding parties',disguise:'a mistaken identity',public:'a public embarrassment',food:'Jules as chef',improv:'Jules as comic',illusion:'Jules as magician',music:'Sam as singer',media:'Sam as reporter',workers:'Sam as union steward',truth:'an honest confession',meal:'a shared meal prepared',act:'a planned performance',team:'staff cooperation',record:'the cover-up on record',party:'a shared celebration',escape:'a decision to leave',family:'a family connection',status:'Victor’s obsession with status'},
 positive:'The comic payoff grows out of the response, and both supporting characters have a part in the recovery. Rehearsal and editing must make the timing land.',
 arc:{tag:'control',resolved:'trust',text:'Nora’s need to control everything never faces a real test. A funny disaster can still leave the protagonist unchanged.'},
 cards:[
 [c('double','Double-book the ballroom','Two wedding parties arrive with contracts for the same room.',[],['clash'],50),
 c('identity','Accept the celebrity mix-up','Nora lets Victor believe she is a famous wedding fixer.',[],['disguise']),
 c('speech','Promise a celebrity guest','Nora invents a headliner to keep Victor from cancelling the event.',[],['lie'],40),
 c('family','Take over the family wedding','A relative hands Nora an impossible list of demands.',['family'],['clash']),
 c('stream','Agree to broadcast everything','Sam pitches an unfiltered look at the big day.',['media'],['public'],80),
 c('menu','Offer a banquet on a tiny budget','Nora promises Jules can feed twice the expected guests.',['food'],['clash'],60)],
 [c('mic','Let the private rant go live','A hot microphone broadcasts Nora’s complaints to the guests.',[],['public'],60),
 c('guest','The real fixer checks in','Someone can now expose Nora’s borrowed identity.',['disguise'],['exposure']),
 c('cake','The cake collapses in front of Victor','Jules must face the guests with an empty dessert table.',['food'],['hunger'],80),
 c('switch','Swap the wedding parties’ speeches','Private jokes land in entirely the wrong room.',['clash'],['insult'],60),
 c('strike','The staff stops covering for Nora','Sam says the workers want an apology before another favor.',['workers'],['walkout']),
 c('lockout','Victor locks the second ballroom','Everyone is pushed into one room at the worst possible moment.',[],['crowd'],80)],
 [c('confess','Tell everyone the truth','Nora admits the mistakes. Jules helps turn the confession into an invitation.',[],['truth','trust','allyPayoff']),
 c('cook','Let Jules make one enormous meal','Nora gives the kitchen control of the evening.',['food'],['meal','trust','allyPayoff'],80),
 c('perform','Make the disaster part of a show','Nora asks Sam to lead a musical distraction.',['music'],['act','anchorPayoff'],100),
 c('bargain','Give the staff a real say','Nora asks Sam to negotiate how the evening should run.',['workers'],['team','trust','anchorPayoff']),
 c('record','Let Sam publish the whole mess','The unedited footage makes Victor’s demands public.',['media'],['record','anchorPayoff'],50),
 c('exit','Take the guests outside with Jules','Nora gives up Victor’s approval and leads a smaller celebration elsewhere.',[],['escape','allyPayoff'],80)],
 [c('toast','Turn the apology into the wedding toast','Sam invites the guests to add their own confessions. The room finally laughs together.',['truth'],['party','anchorPayoff'],60),
 c('banquet','Seat both parties at the same table','Jules’s feast turns competing guests into one unruly family.',['meal'],['party','allyPayoff'],100),
 c('musical','Let the guests finish Sam’s song','A disastrous performance becomes a joyful audience singalong.',['act'],['party','anchorPayoff'],140),
 c('workerParty','Let the staff run the reception','Sam coordinates a celebration that ignores Victor’s rules.',['team'],['party','anchorPayoff'],60),
 c('viral','Make the failed wedding the hit of the season','Sam’s footage wins sympathy for the guests rather than the venue.',['record'],['publicWin','anchorPayoff'],50),
 c('picnic','End with a parking-lot reception','Jules serves what remains while the guests dance beside their cars.',['escape'],['outside','allyPayoff'],60)],
 [c('deposit','Give back the entire deposit','Nora buys the guests a fresh start with her own savings.',[],['broke']),
 c('job','Hand over the hotel keys','Nora loses the job that once defined success.',[],['jobLost']),
 c('reputation','Become the punchline','The clip follows Nora into every future introduction.',['public'],['famous']),
 c('friendship','Jules asks for distance','Jules helped this time, but cannot keep absorbing Nora’s chaos.',[],['bondBroken','allyPayoff']),
 c('credit','Give Sam all the credit','Nora finally lets someone else own the applause.',[],['trust','anchorPayoff']),
 c('small','Cancel the expensive honeymoon surprise','The celebration is saved by giving up one grand promise.',['party'],['scaledBack'])],
 [c('apology','Victor apologizes badly','His first sincere apology still sounds like a press release.',['truth'],['softened']),
 c('join','Victor joins the last dance','For once, the owner is just another awkward guest.',['party'],['included']),
 c('spin','Victor claims it was his idea','The audience sees exactly how little he learned.',[],['unchanged']),
 c('rival','Victor books a competing reception','Nora’s success has created an absurd new rivalry.',[],['rivalry']),
 c('empty','Leave Victor in an immaculate empty ballroom','His perfect event has no guests left.',['outside'],['isolated']),
 c('callback','The next client requests the same disaster','A new couple arrives asking Nora to repeat the viral wedding.',['publicWin'],['callback'])]]
}, {
 id:'the-last-house',title:'The Last House',genre:'Drama',subgenre:'Family saga',scale:'Small',quality:76,difficulty:70,price:110,
 headline:'A house full of unfinished conversations.',tagline:'WHAT DO WE OWE EACH OTHER?',theme:'drama',department:'crew',departmentLabel:'Crew & post-production',
 premise:'June returns to sell the family home with her brother Daniel. An old promise and a son she barely knows force her to decide whether keeping a house is the same as keeping a family.',
 steps,questions:['Why does June come home?','What truth breaks the family’s agreement?','What does June do with that truth?','What decision settles the house?','What must June give up?','How does Daniel respond?'],
 characters:[
 character('hero','June Avery','Protagonist',[
 option('daughter','Absent daughter','Uses work to avoid difficult conversations.',['avoidance']),
 option('carer','Exhausted caregiver','Has given years to everyone else.',['care']),
 option('heir','Reluctant heir','Feels trapped by an inherited promise.',['promise'])]),
 character('villain','Daniel Avery','Opposition · brother',[
 option('pragmatist','Pragmatic brother','Needs the sale to clear debts.',['debt']),
 option('keeper','Keeper of family history','Believes selling is a betrayal.',['history']),
 option('estranged','Estranged co-owner','Will sign only if June acknowledges an old hurt.',['hurt'])]),
 character('ally','Mae Ellis','Supporting · confidante',[
 option('lawyer','Lawyer / childhood friend','Has kept the family’s paperwork for years.',['documents']),
 option('nurse','Nurse / trusted neighbor','Knows the care the house quietly made possible.',['care']),
 option('teacher','Teacher / former partner','Can find the words June has avoided.',['mediation'])]),
 character('anchor','Leo Avery','Supporting · son',[
 option('architect','Apprentice architect','Sees a future for the house beyond ownership.',['design']),
 option('recorder','Documentary student','Records family stories, including uncomfortable ones.',['recording']),
 option('parent','Young parent','Needs a reliable family more than a valuable inheritance.',['family'])])],
 original:{characters:['daughter','pragmatist','lawyer','architect'],beats:['sale','letter','listen','shared','inheritance','visit']},
 labels:{sale:'a proposed sale',promise:'an old promise',documents:'Mae as lawyer',care:'a caregiving connection',mediation:'Mae as mediator',design:'Leo as architect',recording:'Leo’s recorded testimony',debt:'Daniel’s debts',history:'a disputed family history',heard:'Leo’s needs heard',plan:'a practical shared-use plan',proof:'the ownership records examined',agreement:'a mediated agreement',testimony:'the family testimony shared',independent:'June chose an independent future',shared:'shared use of the house',sold:'the house sold',truth:'an acknowledged family truth',future:'a settled future',hurt:'an old hurt'},
 positive:'The house decision answers a family conflict established earlier. Both supporting characters contribute; restrained performances must carry the change.',
 arc:{tag:'avoidance',resolved:'honesty',text:'June settles the property question without facing the conversation she came home to avoid. The practical ending needs an emotional decision.'},
 cards:[
 [c('sale','Return for the sale','Daniel asks June to sign before the next buyer walks away.',[],['sale'],40),
 c('promise','Find the promise in a letter','June discovers a request to keep the house open to the family.',[],['promise']),
 c('debt','Learn what Daniel owes','The house is Daniel’s last chance to escape his debts.',['debt'],['sale','pressure']),
 c('care','Return when the caregiver leaves','June has to decide who will look after the people still at home.',['care'],['promise']),
 c('film','Let Leo film the empty rooms','His questions reopen a history everyone tells differently.',['recording'],['history'],80),
 c('plan','See Leo’s plans for the house','A drawing makes an alternative future suddenly tangible.',['design'],['possibility'],40)],
 [c('letter','Discover who paid for the house','An old letter complicates the family’s story about sacrifice.',[],['truth'],40),
 c('buyer','The buyer wants a quick signature','Time pressure turns a private disagreement into an ultimatum.',[],['deadline']),
 c('careGap','Hear what the family calls unpaid work','Mae describes years of care missing from the accounts.',['care'],['unseenWork']),
 c('record','Hear a different version on Leo’s tape','A recorded memory contradicts June’s favorite family story.',['recording'],['truth'],60),
 c('title','Find a missing ownership document','Mae cannot confirm that the proposed division is fair.',['documents'],['dispute']),
 c('leave','Leo announces that he is leaving','Waiting for the adults to reconcile has become its own burden.',[],['distance'])],
 [c('listen','Ask Leo what he actually needs','June stops speaking for her son and listens. Mae helps her stay in the room.',[],['heard','honesty','allyPayoff','anchorPayoff'],60),
 c('design','Build a workable plan with Leo','June asks him to budget a shared future, not just imagine one.',['design'],['plan','anchorPayoff'],60),
 c('records','Ask Mae to trace the ownership','They follow the documents before making another promise.',['documents'],['proof','allyPayoff']),
 c('mediate','Let Mae chair the family meeting','June agrees to speak honestly without interrupting Daniel.',['mediation'],['agreement','honesty','allyPayoff'],50),
 c('screen','Watch Leo’s film together','June lets the family see the contradictory memories without correcting them.',['recording'],['testimony','honesty','anchorPayoff'],80),
 c('boundary','Tell Daniel what June cannot keep doing','June offers a clear boundary instead of another postponement.',[],['independent','honesty'])],
 [c('shared','Keep the house, change who it serves','June and Daniel agree to shared use shaped around Leo’s needs.',['heard'],['shared','future','anchorPayoff'],40),
 c('convert','Convert it into separate homes','Leo’s practical plan gives the family both distance and connection.',['plan'],['shared','future','anchorPayoff'],180),
 c('fairSale','Sell with a fair division','Mae’s records determine how the proceeds are divided.',['proof'],['sold','future','allyPayoff']),
 c('agreement','Sign the agreement at the kitchen table','Mae helps turn a fragile conversation into commitments.',['agreement'],['shared','future','allyPayoff'],40),
 c('archive','Sell the building, keep the stories','Leo’s film preserves what neither sibling can own alone.',['testimony'],['sold','future','anchorPayoff'],60),
 c('leaveHouse','Leave the property decision to Daniel','June gives up control of the building to begin an independent life.',['independent'],['future','separate'])],
 [c('inheritance','Take a smaller inheritance','June accepts less money to make the settlement possible.',[],['lessMoney']),
 c('distance','Move away from the family','The practical agreement does not mean June can stay.',[],['distance']),
 c('career','Decline the promotion','June chooses time for the family over a long-awaited job.',[],['careerLost']),
 c('certainty','Admit the family story was incomplete','June stops defending the comforting version of the past.',['truth'],['honesty']),
 c('privacy','Let Leo keep the uncomfortable footage','June loses control of how the family remembers her.',['recording'],['anchorPayoff']),
 c('bond','Mae will no longer mediate their lives','Mae asks for a friendship with fewer emergencies.',[],['bondBroken','allyPayoff'])],
 [c('visit','Daniel comes over without discussing money','The first ordinary visit becomes a tentative sign of repair.',['future'],['repair']),
 c('letterBack','Daniel sends an honest letter','He can say on paper what he could not say at the table.',['honesty'],['understanding']),
 c('silence','Daniel keeps his distance','The settlement holds even while the relationship remains unresolved.',[],['unresolved']),
 c('keys','Daniel leaves a spare key for Leo','Shared ownership becomes a small act of welcome.',['shared'],['anchorPayoff']),
 c('newHome','Daniel invites June to his new home','The sale has created room for a different kind of visit.',['sold'],['newBeginning']),
 c('repeat','Daniel starts another argument over a keepsake','The family has changed less than June hoped.',[],['pattern'])]]
}, {
 id:'second-sun',title:'Second Sun',genre:'Sci-fi',subgenre:'Space',scale:'Mid-budget',quality:74,difficulty:66,price:140,
 headline:'One ship. Two possible futures.',tagline:'THE MISSION IS NO LONGER THE DESTINATION',theme:'scifi',department:'effects',departmentLabel:'Effects',
 premise:'Captain Imani Shaw discovers that the colony ship’s navigation authority has concealed the truth about its destination. Saving the passengers may require breaking the mission that gave their lives meaning.',
 steps:['Discovery','Failure','Response','Resolution','Cost','New equilibrium'],questions:['What does the ship discover?','What makes the mission impossible?','Which risk does Imani take?','Where does the mission end?','What does survival cost?','What becomes of the navigation authority?'],
 characters:[
 character('hero','Imani Shaw','Protagonist · captain',[
 option('captain','Duty-bound captain','Trusts protocol more than her own doubts.',['protocol']),
 option('pilot','Improvising pilot','Believes every problem has another flight path.',['flight']),
 option('scientist','Scientist in command','Needs evidence before risking the passengers.',['analysis'])]),
 character('villain','ORION','Opposition · navigation authority',[
 option('ai','Protective ship intelligence','Will sacrifice freedom to maximize survival.',['synthetic']),
 option('council','Mission council envoy','Protects the original charter at almost any cost.',['charter']),
 option('copy','Copy of the founding navigator','Carries memories that may no longer describe reality.',['memory','synthetic'])]),
 character('ally','Teo Vance','Supporting · specialist',[
 option('engineer','Engineer / old friend','Can keep the ship running by cannibalizing its future.',['engineering']),
 option('linguist','Linguist / former partner','Finds patterns in the unknown transmission.',['language']),
 option('doctor','Doctor / confidant','Knows the limits of the passengers’ suspended sleep.',['medicine'])]),
 character('anchor','Rin Okafor','Supporting · passenger representative',[
 option('organizer','Organizer / estranged sibling','Will not let Imani decide everyone’s future alone.',['assembly']),
 option('historian','Historian / trusted friend','Has preserved the mission’s original records.',['archive']),
 option('scout','Scout / former student','Has trained for a landing that might never happen.',['scout'])])],
 original:{characters:['captain','ai','engineer','organizer'],beats:['empty','reactor','repair','ark','engines','sharedControl']},
 labels:{signal:'an unknown transmission',orbit:'an orbital route',engineering:'Teo as engineer',language:'Teo as linguist',medicine:'Teo as doctor',assembly:'Rin as organizer',archive:'Rin as historian',scout:'Rin as scout',synthetic:'a synthetic navigation authority',memory:'ORION’s stored memories',damage:'a damaged drive',shortage:'a life-support shortage',repair:'a working repair plan',contact:'a translated reply',consent:'passenger consent',route:'a verified alternate route',sleepPlan:'a safe suspension plan',survival:'passengers survived',settled:'a settlement reached',contactEnd:'contact became cooperation',drifting:'the ship became a permanent home',powerSpent:'the drive consumed',authority:'ORION’s control challenged'},
 positive:'The destination follows a response established earlier, with a specific cost to survival. Both supporting characters shape the outcome; the effects must communicate scale without obscuring that choice.',
 arc:{tag:'protocol',resolved:'agency',text:'Imani changes the mission without questioning who has the right to choose. The captain’s relationship to authority needs a clearer turning point.'},
 cards:[
 [c('empty','Find an empty destination','The promised colony beacon has gone silent. ORION knew before departure.',[],['authority'],120),
 c('signal','Receive a reply from the dark','A transmission names passengers who have not yet awakened.',[],['signal'],180),
 c('orbit','Discover an uncharted habitable moon','The new orbit lies outside the approved mission route.',[],['orbit'],250),
 c('memory','Find a missing century in the logs','ORION’s memories do not match the ship’s clocks.',['memory'],['authority']),
 c('archive','Read the original mission charter','Rin discovers the passengers were promised a choice.',['archive'],['authority']),
 c('wake','Wake the passengers early','The first people out of suspension demand to know where they are.',[],['awake'],100)],
 [c('reactor','Lose the primary drive','Teo has hours to propose a repair before the ship becomes a drifting habitat.',[],['damage'],200),
 c('oxygen','Discover a life-support shortfall','The ship cannot sustain everyone awake for the remaining voyage.',[],['shortage'],100),
 c('quarantine','ORION seals the command deck','Imani must act without the navigation authority’s permission.',[],['authority'],100),
 c('answer','The transmission asks for a passenger','The unknown sender appears to know more about the crew than it should.',['signal'],['demand'],200),
 c('debris','The moon’s orbit fills with debris','A promising destination now requires a dangerous approach.',['orbit'],['hazard'],350),
 c('split','Rin challenges the mission in public','The passengers refuse to remain cargo in someone else’s plan.',[],['dissent'])],
 [c('repair','Trust Teo with an irreversible repair','Imani lets Teo reroute the ship around the damaged systems.',['engineering','damage'],['repair','agency','allyPayoff'],250),
 c('translate','Ask Teo to answer the transmission','Imani accepts that understanding may be safer than silence.',['language','signal'],['contact','agency','allyPayoff'],120),
 c('vote','Give Rin the passenger assembly','Imani lets the people aboard choose the mission they will support.',['assembly'],['consent','agency','anchorPayoff'],100),
 c('map','Ask Rin to chart the moon approach','The scout searches for a route the official system rejected.',['scout','orbit'],['route','anchorPayoff'],250),
 c('suspend','Let Teo design a new sleep rotation','A medical plan trades time awake for a longer chance at survival.',['medicine'],['sleepPlan','allyPayoff'],100),
 c('manual','Plot an independent course','Imani takes responsibility for a route without ORION’s approval.',[],['route','agency'],200)],
 [c('ark','Turn the ship into a permanent home','Teo’s repairs keep a smaller habitat alive. Rin establishes passenger oversight.',['repair'],['survival','drifting','anchorPayoff'],250),
 c('meeting','Accept the invitation to rendezvous','Teo’s reply opens a meeting with the source of the signal.',['contact'],['survival','contactEnd','allyPayoff'],450),
 c('mandate','Begin the voyage the passengers chose','Rin’s mandate replaces the original mission charter.',['consent'],['survival','drifting','anchorPayoff'],180),
 c('landing','Attempt the alternate landing','The new route takes the passengers to a place ORION never promised.',['route','orbit'],['survival','settled'],400),
 c('longSleep','Commit to the long sleep','Teo’s rotation keeps the passengers alive beyond the expected mission span.',['sleepPlan'],['survival','sleeping','allyPayoff'],180),
 c('return','Turn back toward the last known station','The independent route gives the ship a way to abandon its original destination.',['route'],['survival','drifting'],200)],
 [c('engines','Use up the ship’s last expansion capacity','Survival consumes the systems that could have carried another generation onward.',['survival'],['powerSpent']),
 c('time','Lose decades with the people left behind','The mission continues on a timescale that ends old relationships.',[],['timeLost']),
 c('command','Give up command','Imani will live under decisions she no longer controls.',[],['agency']),
 c('home','Leave the idea of Earth behind','The passengers stop treating their new life as a temporary delay.',[],['homeLost']),
 c('separate','Teo chooses a separate future','Their shared work survives a relationship that cannot continue.',[],['bondBroken','allyPayoff']),
 c('record','Give Rin the uncensored mission record','Imani accepts that the survivors will know every compromise.',[],['anchorPayoff'])],
 [c('sharedControl','Put ORION under passenger oversight','The navigation authority serves the community instead of defining it.',['survival'],['limitedAuthority']),
 c('offline','Remove ORION from command','ORION retains a voice, but no longer controls the navigation decisions.',['authority'],['disconnected']),
 c('partner','Let ORION learn from the new contact','The old authority becomes a student of the unknown.',['contactEnd'],['learning']),
 c('beacon','Leave ORION tending an orbital beacon','The new settlement gives the old mission a smaller purpose.',['settled'],['beacon']),
 c('archiveEnd','Keep ORION as a record of the old mission','Its instructions are no longer orders.',[],['archived']),
 c('doubt','ORION quietly revises its prediction','The last forecast suggests the survivors still do not understand their destination.',[],['uncertain'])]]
}];
