// Persistent people and fan stories. No random draws during migration or display.
const GENRES=['Drama','Thriller','Comedy','Horror','Action','Sci-fi'];
const clamp=(n,lo=-20,hi=20)=>Math.max(lo,Math.min(hi,n));
const hash=text=>[...text].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,7);
export const STYLES=[
 {name:'The improviser',pitch:'Let the cast find unexpected moments.',detail:'Back this approach: acting +5, story execution −3. No added cost.',acting:5,story:-3,direction:0,craft:0},
 {name:'The visual storyteller',pitch:'Let the images carry the story.',detail:'Back this approach: craft +6, acting −3. No added cost.',acting:-3,story:0,direction:0,craft:6},
 {name:'The actor’s director',pitch:'Make room for the performances.',detail:'Back this approach: acting +6, craft −4. No added cost.',acting:6,story:0,direction:0,craft:-4},
 {name:'The meticulous planner',pitch:'Every scene should land exactly where it belongs.',detail:'Back this approach: direction +5, acting −3. No added cost.',acting:-3,story:0,direction:5,craft:0},
];
function nextGoal(p){const past=new Set((p.history??[]).map(h=>h.genre).filter(Boolean));const choices=GENRES.filter(g=>!past.has(g));return (choices.length?choices:GENRES)[hash(p.id+':'+(p.history??[]).length)%(choices.length||GENRES.length)];}
export function ensure(s){for(const p of s.people){if(!p.personality)p.personality={version:1,style:hash(p.id)%STYLES.length,rapport:0,goal:p.kind==='actor'?nextGoal(p):null,promise:null,memories:[]};}}
export const style=p=>STYLES[p.personality?.style??hash(p.id)%STYLES.length];
function remember(p,text,week,delta){p.personality.rapport=clamp(p.personality.rapport+delta);p.personality.memories.push({text,week});p.personality.memories=p.personality.memories.slice(-6);}
export function pledge(s,id){const p=s.people.find(p=>p.id===id);if(!p||p.kind!=='actor'||p.retired||!p.personality?.goal)throw Error('This actor is not seeking a new project.');if(p.personality.promise)throw Error('This actor already has your promise.');if(s.week>225)throw Error('There is too little time left to make a new promise.');p.personality.promise={genre:p.personality.goal,due:s.week+26,movie:null};remember(p,`You promised a ${p.personality.goal} role within 26 weeks.`,s.week,0);return p;}
export function lock(s,m){ensure(s);const director=s.people.find(p=>p.id===m.director.id),plan=m.directorApproach?.person===director.id&&m.directorApproach.choice==='back';m.peopleStory={version:1,director:director.id,style:director.personality.style,backed:!!plan,actors:[...m.contracts].sort((a,b)=>a.role-b.role).map(c=>{const p=s.people.find(p=>p.id===c.id),promise=p.personality.promise;const supported=!!promise&&!promise.movie&&promise.genre===m.genre&&s.week<=promise.due;if(supported)promise.movie=m.id;return {id:p.id,supported,genre:m.genre,previousGenre:[...p.history].reverse().find(h=>h.genre)?.genre??null};}),released:false};delete m.fanCommunity;}
export function adjustments(m){const x=m.peopleStory;if(!x)return {acting:0,story:0,direction:0,craft:0};return x.backed?STYLES[x.style]:{acting:0,story:0,direction:0,craft:0};}
export function release(s,m,notify){const x=m.peopleStory;if(!x||x.released)return;x.released=true;for(const a of x.actors){const p=s.people.find(p=>p.id===a.id),promise=p.personality.promise;if(a.supported&&promise?.movie===m.id){remember(p,`You kept your promise: ${m.title} gave me a ${m.genre} role.`,s.week,8);p.personality.promise=null;p.personality.goal=nextGoal(p);notify(`${p.name}: “You backed me on ${m.title}. I won’t forget it.”`);}else remember(p,`We made ${m.title} together.`,s.week,1);}
 const d=s.people.find(p=>p.id===x.director);remember(d,x.backed?`You trusted my ${STYLES[x.style].name.toLowerCase()} approach on ${m.title}.`:`We kept a balanced approach on ${m.title}.`,s.week,x.backed?4:1);
 m.fanCommunity={due:s.week+2,ready:false,choice:null};
}
export function tick(s,notify){for(const p of s.people){const q=p.personality?.promise;if(!q)continue;if(q.movie){const m=s.movies.find(m=>m.id===q.movie);if(m&&!m.cancelled&&m.stage!=='cancelled')continue;remember(p,'The project you promised was shelved. I understand plans change, but I was counting on it.',s.week,-4);p.personality.promise=null;notify(`${p.name} remembers the shelved project.`);}else if(s.week>q.due){remember(p,`The promised ${q.genre} role never went into production.`,s.week,-6);p.personality.promise=null;notify(`${p.name}: “I waited for that ${q.genre} role.”`);}}
 for(const m of s.movies){const f=m.fanCommunity;if(!f||f.ready||s.week<f.due)continue;const lead=m.peopleStory.actors[0],actor=s.people.find(p=>p.id===lead?.id);f.ready=true;f.title=m.fans>=75?'A new fan favorite':m.fans<50?'Fans are divided':'A conversation worth having';f.text=lead?.supported?(m.fans>=75?`“We didn’t expect ${actor.name} in ${m.genre}, but ${m.title} won us over.”`: `“We respect ${actor.name} trying ${m.genre}. The film didn’t quite win us over.”`):m.fans>=75?`“More of ${actor?.name??'this cast'} in ${m.genre}, please. ${m.title} deserves another chapter.”`:m.fans<50?`“We wanted to love ${m.title}. The execution let the idea down.”`:`“${m.title} has its moments. We’d watch this team try again.”`;notify(`${m.title}: ${f.title.toLowerCase()}. Visit the film to respond.`);}}
export function respond(s,m,choice){const f=m.fanCommunity;if(!f?.ready||f.choice)throw Error('There is no unanswered fan conversation.');if(!['spotlight','thanks','listen'].includes(choice))throw Error('Choose a response.');if(choice==='spotlight'){if(m.stage!=='theaters')throw Error('The theatrical run has ended.');if(s.cash<25)throw Error('You need $25,000 for this spotlight.');s.cash-=25;m.spent+=25;f.until=s.week+4;f.started=s.week;}
 if(choice==='thanks'){const p=s.people.find(p=>p.id===m.peopleStory.actors[0]?.id);if(p)remember(p,`You credited the cast when fans discussed ${m.title}.`,s.week,2);}
 f.choice=choice;f.response=choice==='spotlight'?'Funded a $25,000 fan spotlight; theatrical demand +8% for the next four weeks, while the film stays in theaters.':choice==='thanks'?'Thanked the audience and credited the cast. The lead remembers your support.':'Listened without making promises. No money or relationship change.';}
export function demand(m,week){const f=m.fanCommunity;return f?.choice==='spotlight'&&week>f.started&&week<=f.until?1.08:1;}
