import * as Cards from './scifi.js?v=0.36.0';
const hash=text=>[...String(text)].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,17);
const clamp=(n,lo=0,hi=100)=>Math.max(lo,Math.min(hi,n));
const released=m=>['theaters','catalog'].includes(m.stage);
export const BOSSES=[
 {id:'atlas',name:'Walter Briggs',company:'Atlas Pictures',initials:'WB',agenda:'Big openings. Familiar stars.',genres:['Action','Sci-fi'],strength:88},
 {id:'velvet',name:'Rafael Costa',company:'Velvet Lantern Films',initials:'RC',agenda:'Awards first. Everything else second.',genres:['Drama','Comedy'],strength:78},
 {id:'nightowl',name:'Miles Mercer',company:'Night Owl Studios',initials:'MM',agenda:'Original scares. Disciplined budgets.',genres:['Horror','Thriller'],strength:72},
];
export function ensure(s){s.life??={version:1,crew:{loyalty:50,fatigue:0},identity:identity(s),pitches:[],comebacks:{},rivals:{},rivalResults:[],covers:[],lastPitch:-12};for(const b of BOSSES)s.life.rivals[b.id]??={trust:50,owed:false,last:'We share an audience. We do not always share a plan.'};}
export function identity(s){const films=s.movies.filter(released),counts={};for(const m of films)counts[m.genre]=(counts[m.genre]??0)+1;
 return {genres:Object.keys(counts).filter(g=>counts[g]>=3),variety:Object.keys(counts).length,launches:new Set(films.flatMap(m=>m.life?.debutActors??[])).size};
}
export function scriptMultiplier(s,genre){const x=s.life?.identity;return x&&(x.genres.includes(genre)||x.variety>=3)?.9:1;}
export function talentMultiplier(s,p){return s.life?.identity.launches>=3&&p.star<30?.95:1;}
export function checkPitch(s,pitch,genre,cards){const x=s.life?.pitches.find(x=>x.id===pitch);if(!x||x.movie||x.passed||s.week>x.expires||x.genre!==genre||!x.protect.every(([k,v])=>cards?.[k]?.includes(v)))throw Error('This passion pitch is unavailable or its protected cards changed.');return x;}
export function attachPitch(s,m,id){const x=s.life.pitches.find(x=>x.id===id);x.movie=m.id;m.passion={pitch:id,person:x.person,protect:structuredClone(x.protect),due:s.week+26};}
export function passionDiscount(m,p){return m.passion?.person===p.id&&m.passion.protect.every(([k,v])=>m.scifiCards?.[k]?.includes(v))?.75:1;}
export function releasePitch(s,m){if(!m.passion||!['development','packaging'].includes(m.stage))throw Error('This promise is already locked.');const id=m.passion.person,p=s.people.find(x=>x.id===id);m.contracts=m.contracts.filter(c=>c.id!==id);if(m.director?.id===id)m.director=null;p.personality.rapport=clamp(p.personality.rapport-5,-20,20);m.passion=null;}
export function checkGreenlight(s,m){if(m.passion&&(![...m.contracts,m.director].filter(Boolean).some(c=>c.id===m.passion.person)||!m.passion.protect.every(([k,v])=>m.scifiCards?.[k]?.includes(v))||s.week>m.passion.due))throw Error('Keep the pitching talent and protected cards, and start by the promised week—or release the promise and recast.');}
export function comebackEligible(p){return !p.retired&&p.history?.length>0&&p.star<60&&p.history.slice(-2).some(h=>h.score<55);}
export function backComeback(s,m,id){const p=s.people.find(p=>p.id===id);if(!p||!comebackEligible(p)||s.life.comebacks[id]||m.stage!=='packaging'||![...m.contracts,m.director].filter(Boolean).some(c=>c.id===id))throw Error('Choose attached talent seeking a comeback, before filming.');s.life.comebacks[id]={movie:m.id,status:'backed',week:s.week};}
export function lock(s,m){ensure(s);const parent=s.movies.find(x=>x.id===m.parent),old=parent?.scifiCards&&Cards.selected(parent.scifiCards,parent.genre).map(c=>c.name),now=m.scifiCards&&Cards.selected(m.scifiCards,m.genre).map(c=>c.name);
 m.life={version:1,crewHandled:false,crewQuality:s.life.crew.loyalty>=70?2:s.life.crew.loyalty<35?-2:0,debutActors:m.contracts.filter(c=>!(s.people.find(p=>p.id===c.id).history??[]).length).map(c=>c.id),sequel:old&&now?{kept:now.filter(c=>old.includes(c)),new:now.filter(c=>!old.includes(c)),lost:old.filter(c=>!now.includes(c)),ratio:old.filter(c=>now.includes(c)).length/old.length,originalFans:parent.fans}:null,released:false};
}
export function crewDue(s,m){return m.life&&!m.life.crewHandled&&m.delayPlan&&m.progress>=Math.ceil(m.duration*.6)&&m.progress<m.duration&&s.life.crew.fatigue>=35;}
export function crewChoice(s,m,choice){const effects={wait:[6,-30],rework:[1,-15],coverage:[-6,10]},[trust,fatigue]=effects[choice];s.life.crew.loyalty=clamp(s.life.crew.loyalty+trust);s.life.crew.fatigue=clamp(s.life.crew.fatigue+fatigue);m.life.crewOutcome=choice==='wait'?'Nora remembers that you gave the crew time to recover.':choice==='rework'?'Nora appreciated a simpler, achievable shoot.':'Nora remembers pushing an exhausted crew.';}
export function finish(m){const x=m.life?.sequel;if(!x)return;x.reaction=x.new.length===0?'A familiar chapter':m.fans>=x.originalFans?'A fresh direction that connected':x.ratio<.5?'A departure that divided the audience':'Familiar ingredients, a weaker reception';x.demand=m.fans>=x.originalFans?(x.new.length?.08:.04):x.ratio<.5?-.08:0;}
export function openingMultiplier(s,m){const parent=s.movies.find(x=>x.id===m.parent);return 1+(m.life?.sequel?.demand??0)+(parent?.cult?.choice==='convention'?.08:parent?.cult?.choice==='rerelease'&&parent.cult.settled?.04:0)+(m.releaseDeal?.choice==='cinema'?.1:0);}
export function release(s,m){const life=m.life;if(!life||life.released)return;life.released=true;
 if(m.passion){const p=s.people.find(p=>p.id===m.passion.person);p.personality.rapport=clamp(p.personality.rapport+5,-20,20);life.passionOutcome=`${p.name}: “You kept the part that mattered to me.”`;}
 for(const [id,c] of Object.entries(s.life.comebacks)){if(c.movie!==m.id||c.status!=='backed')continue;const p=s.people.find(p=>p.id===id),credit=m.careerChanges.find(x=>x.id===id);if(!credit){c.status='recast';continue;}const success=credit.performance>=75&&m.critics>=70;c.status=success?'comeback':'supported';c.title=m.title;c.week=s.week;if(success){p.star=clamp(p.star+8);p.fee=Math.round(35+p.star*p.star*.35);credit.after=p.star;credit.fee=p.fee;}p.personality.rapport=clamp(p.personality.rapport+(success?6:2),-20,20);c.text=success?`${p.name} found a second act in ${m.title}.`:`${p.name} remembers your support, even though ${m.title} was not the comeback they hoped for.`;}
 s.life.identity=identity(s);
}
function pitch(s){const alive=s.people.filter(p=>!p.retired&&p.personality&&p.star<60).sort((a,b)=>a.id.localeCompare(b.id));if(!alive.length)return;const p=alive[hash(s.seed+':pitch:'+s.week)%alive.length],genre=Cards.genres.includes(p.personality.goal)?p.personality.goal:Cards.genres[hash(p.id)%3],sections=Cards.sections(genre),cards=Object.fromEntries(sections.map((x,i)=>[x.id,[x.cards[hash(p.id+':'+i)%5]]])),protect=[['concept',cards.concept[0]],['tone',cards.tone[0]]];s.life.pitches.push({id:'pitch:'+s.week,person:p.id,genre,cards,protect,expires:Math.min(258,s.week+20),movie:null});s.life.lastPitch=s.week;}
export function cultChoice(s,m,choice){const c=m.cult;if(!c?.ready||c.choice||!['rerelease','convention','leave'].includes(choice))throw Error('No unanswered cult-film invitation.');if(choice==='rerelease'&&m.streamingDeal?.id==='exclusive'&&s.week<=m.streamingDeal.endWeek)throw Error('Wait until the exclusive streaming license ends.');if(choice==='rerelease'&&s.week+2>=260)throw Error('Not enough time remains for a screening.');const cost=choice==='rerelease'?100:choice==='convention'?30:0;if(s.cash<cost)throw Error('Not enough cash for this event.');s.cash-=cost;m.spent+=cost;c.choice=choice;c.due=s.week+2;if(choice!=='rerelease')c.settled=true;}
export function releaseOptions(s,m,week){if(m.stage!=='ready'||m.release!==null||!Number.isInteger(week)||week<=s.week||week>=260)return [];const options=[];
 if(week+1<260)options.push({choice:'cinema',week:week+1,title:'Give Starlight one more week',detail:'+10% opening demand; release one week later.'});
 const rival=s.rivals.find(r=>Math.abs(r.week-week)<=2&&r.week>s.week&&week+3<260&&BOSSES.some(b=>b.id===r.studioId));if(rival){const relation=rivalRelation(s,rival.studioId);if(!relation.owed&&relation.trust>=40)options.push({choice:'truce',week,rival:s.rivals.indexOf(rival),title:'Ask the rival to move',detail:'Their film moves three weeks beyond your opening. You owe a future release-window favor.'});else if(relation.owed&&week+3<260)options.push({choice:'repay',week:week+3,rival:s.rivals.indexOf(rival),title:'Return the release-window favor',detail:'Move three weeks later. Clear the favor and gain 10 trust.'});}
 return options;
}
export function negotiate(s,m,week,choice){const opt=releaseOptions(s,m,week).find(x=>x.choice===choice);if(!opt)throw Error('That release negotiation is unavailable.');const deadline=[s.marsTravel?.deal,...Object.values(s.clients??{}).map(r=>r.deal)].filter(d=>d?.movie===m.id).map(d=>d.due);if(deadline.some(d=>opt.week>d))throw Error('This date would miss a client deadline. Choose another window.');if(opt.rival!==undefined){const r=s.rivals[opt.rival],relation=s.life.rivals[r.studioId];if(choice==='truce'){r.week=week+3;relation.owed=true;setRivalTrust(s,r.studioId,rivalRelation(s,r.studioId).trust-5);relation.last=`We moved ${r.title}. Your studio owes us a release window.`;}else{relation.owed=false;setRivalTrust(s,r.studioId,rivalRelation(s,r.studioId).trust+10);relation.last=`You moved ${m.title} and kept your word.`;}}m.release=opt.week;m.releaseDeal={choice,week:opt.week};}
export function rivalRelation(s,id){const b=BOSSES.find(b=>b.id===id),r=s.life.rivals[id];return {...r,trust:s.relationships?.[b.company]?.trust??r.trust};}
function setRivalTrust(s,id,value){const b=BOSSES.find(b=>b.id===id);s.life.rivals[id].trust=clamp(value);s.relationships??={};s.relationships[b.company]={...(s.relationships[b.company]??{}),trust:clamp(value)};}
export function rivalSupport(s,id){const b=BOSSES.find(x=>x.id===id),r=s.life.rivals[id];if(!b||s.week<(r.nextMeeting??0))throw Error('This rival is not ready for another meeting.');if(s.cash<50)throw Error('A joint filmmaker showcase costs $50,000.');s.cash-=50;setRivalTrust(s,id,rivalRelation(s,id).trust+10);r.nextMeeting=s.week+26;r.last='We backed a filmmaker showcase together. A useful start.';}
export function tick(s){ensure(s);const active=s.movies.filter(m=>m.stage==='filming'&&!m.delayPlan?.remaining).length;s.life.crew.fatigue=clamp(s.life.crew.fatigue+(active?Math.min(16,active*8):-10));
 if(s.week>=4&&s.week<220&&s.week-s.life.lastPitch>=16&&s.life.pitches.filter(p=>!p.passed&&!p.movie&&p.expires>=s.week).length<2)pitch(s);
 for(const [id,c]of Object.entries(s.life.comebacks))if(c.status==='backed'&&s.movies.find(m=>m.id===c.movie)?.cancelled){c.status='shelved';c.text='The comeback project was shelved.';}
 for(const m of s.movies){if(m.cancelled&&m.passion&&!m.passion.failed){m.passion.failed=true;const p=s.people.find(p=>p.id===m.passion.person);p.personality.rapport=clamp(p.personality.rapport-5,-20,20);}if(m.stage==='catalog'&&!m.cult&&m.fans>=70&&m.receipts<m.spent&&s.week-m.release>=16+hash(m.id)%9)m.cult={ready:true,week:s.week,choice:null};const c=m.cult;if(c?.choice==='rerelease'&&!c.settled&&s.week>=c.due){const gross=120+hash(m.id+':screening')%241,entitlement=gross*(m.share??0),recovered=Math.min(m.recoupRemaining??0,entitlement),receipts=entitlement-recovered;const contracts=[...(m.contracts??[]),...(m.director?[m.director]:[])],payout=receipts*contracts.reduce((n,x)=>n+(x.grossShare??0),0);m.recoupRemaining=Math.max(0,(m.recoupRemaining??0)-recovered);m.recouped=(m.recouped??0)+recovered;m.gross+=gross;m.receipts+=receipts;m.spent+=payout;s.cash+=receipts-payout;m.participationPaid=(m.participationPaid??0)+payout;for(const x of contracts)x.participationPaid=(x.participationPaid??0)+receipts*(x.grossShare??0);c.gross=gross;c.receipts=receipts;c.payout=payout;c.settled=true;}}
 for(const [i,r]of s.rivals.entries()){if(r.week>s.week||s.life.rivalResults.some(x=>x.key===i))continue;const b=BOSSES.find(b=>b.id===r.studioId)??BOSSES[0];s.life.rivalResults.push({key:i,week:r.week,studio:b.id,title:r.title,critics:clamp(r.strength-12+hash(r.title)%23,20,99),fans:clamp(r.strength-8+hash(r.title+':fans')%17,20,99),gross:Math.round(r.strength*r.strength/2)});}
 if(s.life.poach&&!s.life.poach.choice&&s.week>s.life.poach.expires){s.life.poach.choice='pass';resolvePoach(s,s.life.poach);}
 if(s.week%26===13&&(!s.life.poach||s.life.poach.choice)){const candidates=s.people.filter(p=>p.kind==='actor'&&!p.retired&&p.history.length&&!p.bookings.some(b=>s.week<b.end&&s.week+6>b.start));if(candidates.length){const person=candidates[hash(s.week)%candidates.length],boss=BOSSES[hash(person.id+s.week)%3];s.life.poach={week:s.week,person:person.id,studio:boss.id,expires:s.week+2,choice:null};}}
 if(s.week>0&&s.week%52===0)yearbook(s,s.week/52-1);
}
export function poachResponse(s,choice){const x=s.life.poach;if(!x||x.choice||!['retain','pass'].includes(choice))throw Error('No rival offer is waiting.');if(choice==='retain'){if(s.cash<50)throw Error('A first-look retainer costs $50,000.');s.cash-=50;x.choice='retain';s.people.find(p=>p.id===x.person).personality.rapport=clamp(s.people.find(p=>p.id===x.person).personality.rapport+3,-20,20);}else{x.choice='pass';resolvePoach(s,x);}}
function resolvePoach(s,x){const p=s.people.find(p=>p.id===x.person);x.settled=true;if(p.retired||p.bookings.some(b=>s.week<b.end&&s.week+4>b.start)){x.result='Existing commitments took priority.';return;}p.bookings.push({start:s.week,end:s.week+4,movie:'rival:'+x.week});x.result=p.name+' took a four-week shoot with '+BOSSES.find(b=>b.id===x.studio).company+'.';}
export function yearbook(s,yearIndex){const year=2026+yearIndex;if(s.life.covers.some(x=>x.year===year))return;const films=s.movies.filter(m=>released(m)&&m.release>=yearIndex*52&&m.release<(yearIndex+1)*52),rivals=s.life.rivalResults.filter(r=>r.week>=yearIndex*52&&r.week<(yearIndex+1)*52);
 const rank=rows=>rows.length?rows.reduce((n,m)=>n+(m.critics+m.fans)/2,0)/rows.length+Math.min(20,rows.length*4):0;
 const studios=[{name:s.name,score:rank(films)},...BOSSES.map(b=>({name:b.company,score:rank(rivals.filter(r=>r.studio===b.id))}))].filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
 const breakout=films.flatMap(m=>(m.careerChanges??[]).map(c=>({...c,movie:m.title}))).filter(c=>s.people.find(p=>p.id===c.id)?.kind==='actor'&&c.after>c.before).sort((a,b)=>(b.after-b.before)-(a.after-a.before))[0];
 const hits=films.filter(m=>m.receipts>m.spent).sort((a,b)=>b.receipts/Math.max(1,b.spent)-a.receipts/Math.max(1,a.spent));const losses=films.filter(m=>m.stage==='catalog'&&m.spent>m.receipts).sort((a,b)=>(b.spent-b.receipts)-(a.spent-a.receipts));
 s.life.covers.unshift({year,week:s.week,studio:studios[0]?.name??'No eligible studio',breakout:breakout?{name:s.people.find(p=>p.id===breakout.id).name,movie:breakout.movie,gain:Math.round(breakout.after-breakout.before)}:null,hit:hits[0]?{title:hits[0].title,ratio:Number((hits[0].receipts/hits[0].spent).toFixed(2))}:null,loss:losses[0]?{title:losses[0].title,amount:losses[0].spent-losses[0].receipts}:null,films:films.length});
}
