import test from 'node:test';import assert from 'node:assert/strict';
import * as E from '../engine.js';import * as C from '../collection.js';import * as CL from '../clients.js';import * as H from './helpers/life-fixture.js';
function draft(s){const d=C.blank(s);Object.assign(d,{setting:'Small Town',problem:'A Plea for Help',ending:'A Costly Victory'});Object.assign(d.characters[0],{persona:'Outsider',trait:'Idealistic'});return d;}
function unlock(s){s.prestige=100;C.ensure(s);for(const f of Object.keys(C.FAMILIES))while(C.preview(s,f).length)C.claim(s,f);}
test('ten permanent starter cards, 20 per shared deck, and no locked-card bypass',()=>{const s=E.newGame(42),d=draft(s);assert.equal(Object.values(s.collection.owned).flat().length,10);for(const cards of Object.values(C.DECKS)){assert.equal(cards.length,20);assert.equal(new Set(cards).size,20);}assert(C.valid(d,s));d.characters.push({...d.characters[0],role:'Ally'});assert(C.valid(d,s));d.genre='Horror';assert(!C.valid(d,s));assert.throws(()=>E.act(s,'cardMovie',{cards:d,title:'Locked',scale:'Small'}),/own/);assert.equal(s.movies.length,0);});
test('prestige rewards are chooseable, persist, never duplicate and cannot be farmed',()=>{const s=E.newGame(42);assert.throws(()=>C.claim(s,'faces'),/prestige/);s.prestige=1;const expected=C.preview(s,'finale');assert.deepEqual(E.act(s,'claimPack',{family:'finale'}),expected);assert.equal(C.credits(s),0);assert.throws(()=>C.claim(s,'finale'),/prestige/);s.prestige=0;assert.equal(C.credits(s),0);s.prestige=1;assert.equal(C.credits(s),0);s.prestige=5;assert.equal(C.credits(s),2);const restored=E.migrateSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored.collection,s.collection);unlock(s);assert.equal(Object.values(s.collection.owned).flat().length,140);for(const d of Object.values(s.collection.owned))assert.equal(new Set(d).size,d.length);});
test('starter movie completes real production and release; outcomes guide editable sequels',()=>{const s=E.newGame(42),d=draft(s);unlock(s);d.characters[0].outcome='Dies';const m=E.act(s,'cardMovie',{cards:d,title:'The Last Favor',scale:'Small'});assert(m.movieCards&&!m.scifiCards&&!m.acts&&!m.narrativePack);assert.deepEqual(m.roles,['Lead']);for(let i=0;i<3;i++)E.act(s,'next');H.cast(s,m);H.greenlight(s,m);H.wrap(s,m);H.release(s,m);assert(Number.isFinite(m.fans)&&Number.isFinite(m.critics));assert(m.cardReception);s.cash=10000;s.notices=[];E.act(s,'sequel',{id:m.id});const n=s.movies.at(-1);assert.equal(n.movieCards.characters[0].outcome,'');assert.equal(m.movieCards.characters[0].outcome,'Dies');assert.equal(C.continuity(m.movieCards,n.movieCards).length,1);const changed=structuredClone(n.movieCards);changed.characters[0].name='The Successor';E.act(s,'cardRewrite',{id:n.id,cards:changed});assert.equal(C.continuity(m.movieCards,n.movieCards).length,0);for(let i=0;i<3;i++){s.notices=[];E.act(s,'next');}H.cast(s,n);H.greenlight(s,n);assert.equal(n.stage,'filming');assert.throws(()=>E.act(s,'cardRewrite',{id:n.id,cards:changed}));});
test('arrest and escape work on every role, death continuity permits a prequel',()=>{const s=E.newGame(4);unlock(s);for(const role of C.ROLES){const d=draft(s);if(role!=='Lead')d.characters.push({...d.characters[0],role});const c=d.characters.at(-1);for(const outcome of C.DECKS.outcome){c.outcome=outcome;assert(C.valid(d,s));}}const d=draft(s);d.characters[0].outcome='Dies';assert.equal(C.continuity(d,C.sequel(d),'prequel').length,0);});
test('client briefs match the universal collection and are locked until buildable',()=>{const s=E.newGame(42);assert(CL.available(s,'starlight'));assert(!CL.available(s,'lantern'));const d=draft(s);d.genre='Adventure';const m=E.act(s,'cardMovie',{cards:d,title:'The Call',scale:'Small'});E.act(s,'clientAccept',{client:'starlight'});E.act(s,'clientBind',{client:'starlight',id:m.id});assert(CL.matches(m,CL.definition('starlight')));for(let i=0;i<3;i++)E.act(s,'next');H.cast(s,m);H.greenlight(s,m);H.wrap(s,m);H.release(s,m);assert.equal(s.clients.starlight.wins,1);assert.equal(m.sponsorIncome,562.5);});
test('all genres evaluate finite scores; more owned cards do not increase reviews',()=>{const s=E.newGame(42);unlock(s);const m={movieCards:draft(s),scriptQuality:65,performances:[70],directorPerformance:60,craft:55,quality:63};for(const g of C.DECKS.genre){m.movieCards.genre=g;assert(C.valid(m.movieCards,s));const r=C.evaluate(m);assert(Number.isFinite(r.fans)&&Number.isFinite(r.critics));}const a=C.evaluate(m);m.movieCards.characters.push({...m.movieCards.characters[0],role:'Ally'});assert.deepEqual(C.evaluate(m),a);});
test('six character roles cast correctly and rewriting remaps retained contracts',()=>{const s=E.newGame(42);unlock(s);s.cash=100000;const d=draft(s);for(const role of C.ROLES.slice(1))d.characters.push({role,persona:'Expert',trait:'',outcome:'',name:role});const m=E.act(s,'cardMovie',{cards:d,title:'The Ensemble',scale:'Small'});for(let i=0;i<3;i++)E.act(s,'next');H.cast(s,m);assert.equal(m.contracts.length,6);const kept=m.contracts.find(c=>c.role===4).id;const revised=structuredClone(d);revised.characters.splice(3,1);revised.characters[0].name='New Lead';E.act(s,'cardRewrite',{id:m.id,cards:revised});assert.equal(m.contracts.length,4);assert.equal(m.contracts.find(c=>c.id===kept).role,3);assert(!m.contracts.some(c=>c.role===0));assert.deepEqual(E.migrateSave(JSON.parse(JSON.stringify(s))).movies.at(-1).movieCards,revised);});
test('new passion pitches use owned universal cards and bind to the created film',()=>{const s=E.newGame(42);for(let i=0;i<4;i++)E.act(s,'next');const pitch=s.life.pitches[0];assert(C.valid(pitch.movieCards,s));const m=E.act(s,'cardMovie',{title:'A Personal Story',scale:'Small',cards:pitch.movieCards,pitch:pitch.id});assert.equal(m.passion.pitch,pitch.id);const p=E.person(s,pitch.person);assert(E.quote(s,p,m).high<E.quote(s,p,{...m,passion:null}).high);});
