import test from 'node:test';import assert from 'node:assert/strict';import * as E from '../engine.js';import * as C from '../commissions.js';import * as D from '../delays.js';import * as SF from '../scifi.js';
function cards(){const d=Object.fromEntries(SF.SECTIONS.map(x=>[x.id,[x.cards[0]]]));d.setting=['Colony'];return d;}
function setup(){const s=E.newGame(7);E.act(s,'commissionAccept');E.act(s,'original',{title:'New Horizons',genre:'Sci-fi',subgenre:E.GENRES['Sci-fi'][0],scale:'Small',scifiCards:cards()});const m=s.movies[0];E.act(s,'commissionBind',{id:m.id});for(let i=0;i<3;i++){s.notices=[];E.act(s,'next');}const actors=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee);for(let role=0;role<m.roles.length;role++){const p=actors[role];E.act(s,'audition',{id:m.id,person:p.id,role});E.act(s,'hire',{id:m.id,person:p.id,role,offer:E.quote(s,p,m,role).high});}const p=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:p.id});E.act(s,'hire',{id:m.id,person:p.id,offer:E.quote(s,p,m).high});E.act(s,'greenlight',{id:m.id,sets:300,crew:350,effects:200,duration:8});return {s,m};}
function finish(s,m){for(let i=0;i<50&&m.stage!=='ready';i++){if(m.event)E.act(s,'event',{id:m.id,choice:m.event.kind==='delay'?'wait':'pay'});s.notices=[];E.act(s,'next');}assert.equal(m.stage,'ready');}
test('commission release pays once into studio and film receipts, never box office',()=>{const {s,m}=setup();finish(s,m);assert(m.delayPlan.elapsed>=2);E.act(s,'setRelease',{id:m.id,release:s.week+1});E.act(s,'confirmMarketing',{id:m.id,none:true});E.act(s,'distribute',{id:m.id,deal:'secure'});const before=structuredClone(s),other=before.movies[0];before.marsTravel.deal=null;s.notices=[];before.notices=[];E.act(s,'next');E.act(before,'next');assert.equal(m.sponsorIncome,600);assert.equal(s.marsTravel.wins,1);assert.equal(m.gross,other.gross);assert(Math.abs(s.cash-before.cash-600)<1e-8);assert(Math.abs(m.receipts-other.receipts-600)<1e-8);const state=JSON.stringify(s);C.deliver(s,m,()=>{});assert.equal(JSON.stringify(s),state);assert.deepEqual(E.migrateSave(JSON.parse(state)).marsTravel,s.marsTravel);});
test('extension reduces payout, allows eight weeks and rejects duplicate/late requests atomically',()=>{const {s}=setup(),due=s.marsTravel.deal.due;E.act(s,'commissionExtend');assert.equal(s.marsTravel.deal.due,due+8);assert.equal(s.marsTravel.deal.payment,480);const before=JSON.stringify(s);assert.throws(()=>E.act(s,'commissionExtend'));assert.equal(JSON.stringify(s),before);const t=E.newGame(2);E.act(t,'commissionAccept');t.week=t.marsTravel.deal.due-3;assert.throws(()=>E.act(t,'commissionExtend'));});
test('missed, cancelled and wrong-card deals pay nothing; two failures stop future offers',()=>{const {s,m}=setup();m.scifiCards.setting=['Earth'];m.stage='theaters';m.release=s.week;const cash=s.cash;C.deliver(s,m,()=>{});assert.equal(s.cash,cash);assert.equal(s.marsTravel.strikes,1);s.week=s.marsTravel.nextOffer;E.act(s,'commissionAccept');s.week=s.marsTravel.deal.due+1;C.tick(s,()=>{});assert.equal(s.marsTravel.strikes,2);s.week+=52;assert.equal(C.offer(s),false);const b=E.newGame(1);E.act(b,'commissionAccept');E.act(b,'original',{title:'Cancelled',genre:'Sci-fi',subgenre:E.GENRES['Sci-fi'][0],scale:'Small',scifiCards:cards()});const n=b.movies[0];E.act(b,'commissionBind',{id:n.id});E.act(b,'cancel',{id:n.id});C.tick(b,()=>{});assert.equal(b.marsTravel.strikes,1);});
test('declining is not a failure and invalid attachment cannot mutate a deal',()=>{const s=E.newGame(2);E.act(s,'commissionDecline');assert.equal(s.marsTravel.strikes,0);assert.equal(C.offer(s),false);s.week=12;E.act(s,'commissionAccept');const before=JSON.stringify(s);assert.throws(()=>E.act(s,'commissionAccept'));assert.throws(()=>C.bind(s,{genre:'Drama',stage:'packaging'}));assert.equal(JSON.stringify(s),before);});
test('pause stops progress, charges only holding costs and preserves quality when waiting',()=>{const {s,m}=setup();while(!m.event){s.notices=[];E.act(s,'next');}assert.equal(m.event.kind,'delay');const p=E.delayChoices(s,m)[0],progress=m.progress,penalty=m.penalty;E.act(s,'event',{id:m.id,choice:p.choice});const spent=m.spent;s.notices=[];E.act(s,'next');assert.equal(m.progress,progress);assert.equal(m.delayPlan.remaining,p.weeks-1);assert(Math.abs(m.spent-spent-m.weekly*.1)<1e-8);assert.equal(m.penalty,penalty);assert.deepEqual(E.migrateSave(JSON.parse(JSON.stringify(s))).movies[0].delayPlan,m.delayPlan);});
test('booking conflicts extend the pause and resumed reservations do not overlap other commitments',()=>{const {s,m}=setup();while(!m.event){s.notices=[];E.act(s,'next');}const actor=E.person(s,m.contracts[0].id),end=s.week+12;actor.bookings.push({start:s.week+4,end,movie:null});const choice=D.plan(s,m,'wait');assert(choice.conflictWeeks>0);D.resolve(s,m,'wait');for(const p of [...m.contracts,m.director].map(c=>E.person(s,c.id))){const future=p.bookings.filter(b=>b.movie===m.id&&b.end>s.week);for(const a of future)for(const b of p.bookings.filter(b=>b.movie!==m.id))assert(!(a.start<b.end&&a.end>b.start));}assert.equal(choice.resume,end);});
test('creative workarounds trade quality for time, invalid responses do not mutate, sequels reset delays',()=>{const {s,m}=setup();while(!m.event){s.notices=[];E.act(s,'next');}const before=JSON.stringify(s);assert.throws(()=>E.act(s,'event',{id:m.id,choice:'buyout'}));assert.equal(JSON.stringify(s),before);const x=E.delayChoices(s,m).at(-1);E.act(s,'event',{id:m.id,choice:x.choice});assert(m.penalty>=x.damage);finish(s,m);m.stage='theaters';m.fans=70;E.act(s,'sequel',{id:m.id});const sequel=s.movies.at(-1);assert.equal(sequel.delayPlan,undefined);const original=JSON.stringify(m.scifiCards),d=cards();d.setting=['Deep Space','Colony'];E.act(s,'scifiRewrite',{id:sequel.id,cards:d});assert.equal(sequel.stage,'development');assert.deepEqual(sequel.scifiCards,d);assert.equal(JSON.stringify(m.scifiCards),original);});
test('old in-progress films retain their original timing; existing sci-fi sequels can adopt cards',()=>{const {s,m}=setup();delete m.delayPlan;assert.equal(D.due(m),undefined);m.stage='theaters';m.fans=70;delete m.scifiCards;E.act(s,'sequel',{id:m.id});const n=s.movies.at(-1);E.act(s,'scifiRewrite',{id:n.id,cards:cards()});assert.deepEqual(n.scifiCards,cards());assert.equal(n.stage,'development');});
test('a commissioned film cannot collect before release; the deadline week itself qualifies',()=>{const {s,m}=setup(),before=JSON.stringify(s);C.deliver(s,m,()=>{});assert.equal(JSON.stringify(s),before);s.week=s.marsTravel.deal.due;m.stage='theaters';m.release=s.week;C.tick(s,()=>{});assert(s.marsTravel.deal);C.deliver(s,m,()=>{});assert.equal(s.marsTravel.wins,1);assert.equal(m.sponsorIncome,600);});
test('commission attachment is final and late offers are unavailable',()=>{const {s}=setup(),before=JSON.stringify(s);assert.throws(()=>C.bind(s,{id:'another',genre:'Sci-fi',stage:'packaging'}));assert.equal(JSON.stringify(s),before);const late=E.newGame(7);late.week=220;assert.equal(C.offer(late),false);assert.throws(()=>E.act(late,'commissionAccept'));});
test('a paused shoot does not stop another project entering packaging',()=>{const {s,m}=setup();while(!m.event){s.notices=[];E.act(s,'next');}E.act(s,'event',{id:m.id,choice:'wait'});E.act(s,'original',{title:'Other project',genre:'Drama',subgenre:E.GENRES.Drama[0],scale:'Small'});const other=s.movies.at(-1);other.ready=s.week+1;const progress=m.progress;s.notices=[];E.act(s,'next');assert.equal(m.progress,progress);assert.equal(other.stage,'packaging');});
