import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../engine.js';
import * as N from '../narrative.js';
const specs=N.authoredSpecs().filter(s=>s.narrativePack!=='signal-ash');
function buy(spec){const s=E.newGame(7);E.act(s,'buy',{script:spec.id});return [s,s.movies[0]];}
for(const spec of specs){
 const pack=N.packFor(spec.narrative);
 test(`${spec.genre}: complete draft, genre-specific cast and production department`,()=>{assert(E.GENRES[spec.genre].includes(spec.subgenre));const e=N.evaluate(spec.narrative);assert(e.valid);assert(e.effects>0);assert.equal(e.department,spec.genre==='Sci-fi'?'effects':'crew');assert(e.links.length>0);assert(!/Alex|Mara|Voss|Eli/.test(e.weakness));assert.equal(N.executionPenalty(spec.narrative,{[e.department]:e.effects}),0);assert.equal(N.executionPenalty(spec.narrative,{[e.department]:0}),Math.min(8,e.effects/100));assert.equal(pack.characters.length,4);assert(pack.cards.every(c=>c.length>=6));});
 test(`${spec.genre}: 972 routes across all character presets have no dead ends`,()=>{let paths=0;const reached=new Set();for(const a of pack.characters[0].options)for(const b of pack.characters[1].options)for(const c of pack.characters[2].options)for(const d of pack.characters[3].options)for(let variant=0;variant<12;variant++){const draft=structuredClone(spec.narrative);draft.characters=[a.id,b.id,c.id,d.id];for(let step=0;step<6;step++){const choices=N.choices(draft,step).filter(c=>!c.lock);assert(choices.length,`Dead end: ${JSON.stringify(draft)}, step ${step}`);draft.beats[step]=choices[(variant+step)%choices.length].id;choices.forEach(c=>reached.add(step+':'+c.id));}assert(N.evaluate(draft).valid);paths++;}assert.equal(paths,972);for(let i=0;i<6;i++)for(const c of pack.cards[i])assert(reached.has(i+':'+c.id),`Unreached card ${c.id}`);});
 test(`${spec.genre}: rewrites restore purchased story, reject other packs and retain locks`,()=>{const [s,m]=buy(spec),cash=s.cash,original=structuredClone(m.narrative),d=structuredClone(original);d.beats[4]=pack.cards[4].find(c=>c.id!==d.beats[4]&&!N.choices(d,4).find(x=>x.id===c.id).lock).id;E.act(s,'storyRewrite',{id:m.id,draft:d});assert.equal(s.cash,cash-50);E.act(s,'storyRewrite',{id:m.id,restore:true});assert.deepEqual(m.narrative,original);const before=JSON.stringify(s);assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:N.originalDraft()}));assert.equal(JSON.stringify(s),before);const invalid=structuredClone(original);invalid.beats[2]='not-a-choice';assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:invalid}));assert.equal(JSON.stringify(s),before);m.stage='filming';assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:d}));});
 test(`${spec.genre}: real four-role production and release remain affordable`,()=>{const [s,m]=buy(spec);const actors=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee);for(let role=0;role<4;role++){const p=actors[role];E.act(s,'audition',{id:m.id,person:p.id,role});E.act(s,'hire',{id:m.id,person:p.id,role,offer:E.quote(s,p,m,role).high});}const p=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:p.id});E.act(s,'hire',{id:m.id,person:p.id,offer:E.quote(s,p,m).high});const e=N.evaluate(m.narrative);E.act(s,'greenlight',{id:m.id,sets:300,crew:350,effects:100,[e.department]:Math.max(350,e.effects),duration:8});for(let i=0;i<16&&m.stage!=='ready';i++){if(m.event)E.act(s,'event',{id:m.id,choice:'pay'});s.notices=[];E.act(s,'next');}assert.equal(m.stage,'ready');assert(s.cash>0);assert.equal(N.executionPenalty(m.narrative,m.budget),0);E.act(s,'setRelease',{id:m.id,release:s.week+1});E.act(s,'confirmMarketing',{id:m.id,none:true});E.act(s,'distribute',{id:m.id,deal:'secure'});s.notices=[];E.act(s,'next');assert.equal(m.stage,'theaters');assert(Number.isFinite(m.fans));assert(Number.isFinite(m.critics));assert.equal(m.performances.length,4);const saved=E.migrateSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(saved.movies[0].narrative,spec.narrative);});
}
test('existing Signal Ash ownership adds only the three new specs; refreshing never duplicates',()=>{const s=E.newGame(7);E.act(s,'buy',{script:'spec-signal-ash'});s.market=s.market.filter(m=>!m.narrativePack);const before=JSON.stringify(s.movies),rng=s.rng,cash=s.cash;E.ensureNarrativeSpec(s);E.ensureNarrativeSpec(s);assert.equal(s.market.filter(m=>m.narrativePack).length,3);assert.equal(JSON.stringify(s.movies),before);assert.equal(s.rng,rng);assert.equal(s.cash,cash);});
