import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../engine.js';
import * as N from '../narrative.js';
const fixture=()=>{const s=E.newGame(7);E.act(s,'buy',{script:'spec-signal-ash'});return [s,s.movies[0]];};
test('authored spec is complete, unique and survives existing-save loading',()=>{const [s,m]=fixture();assert(N.evaluate(m.narrative).valid);assert.equal(m.roles.length,4);const cash=s.cash;E.ensureNarrativeSpec(s);assert(!s.market.some(x=>x.narrativePack==='signal-ash'));const old=E.newGame(3);old.market=old.market.filter(x=>!x.narrativePack);E.ensureNarrativeSpec(old);E.ensureNarrativeSpec(old);assert.equal(old.market.filter(x=>x.narrativePack).length,4);assert.equal(s.cash,cash);});
test('earlier changes retain downstream choices and reject incompatible approval atomically',()=>{const [s,m]=fixture(),d=structuredClone(m.narrative);d.characters[2]='partner';assert.equal(d.beats[1],'stolen');assert(N.evaluate(d).errors.some(x=>x.step===1));const before=JSON.stringify(s);assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:d}));assert.equal(JSON.stringify(s),before);});
test('valid rewrite charges once, restores actual original and never changes talent or biases',()=>{const [s,m]=fixture(),original=structuredClone(m.narrative),people=JSON.stringify(s.people),cash=s.cash;const d=structuredClone(original);d.beats[4]='sacrifice';E.act(s,'storyRewrite',{id:m.id,draft:d});assert.equal(s.cash,cash-50);assert.equal(JSON.stringify(s.people),people);assert.equal(m.audienceBias,0);assert.equal(m.criticBias,0);assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:d}));E.act(s,'storyRewrite',{id:m.id,restore:true});assert.deepEqual(m.narrative,original);assert.equal(s.cash,cash-50);m.stage='filming';assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,draft:d}));});
test('causal report reads actual setups and execution pressure is bounded',()=>{const d=N.originalDraft(),e=N.evaluate(d);assert(e.links.some(l=>l.from===2&&l.to===3&&l.tag==='countermeasure'));assert.equal(e.effects,250);assert.equal(N.executionPenalty(d,{effects:250}),0);assert.equal(N.executionPenalty(d,{effects:0}),2.5);d.beats=['signal','orbit','improvise','world','sacrifice','kill'];assert(N.evaluate(d).valid);assert.equal(N.executionPenalty(d,{effects:0}),8);assert(N.evaluate(d).effects>1000);});
test('972 sampled paths have valid next choices across all character combinations',()=>{let paths=0;for(const h of N.CAST[0].options)for(const v of N.CAST[1].options)for(const a of N.CAST[2].options)for(const b of N.CAST[3].options){for(let variant=0;variant<12;variant++){const d=N.originalDraft();d.characters=[h.id,v.id,a.id,b.id];for(let step=0;step<6;step++){const available=N.choices(d,step).filter(c=>!c.lock);assert(available.length,`dead end ${JSON.stringify(d)} at ${step}`);d.beats[step]=available[(variant+step)%available.length].id;}assert(N.evaluate(d).valid);paths++;}}assert.equal(paths,972);});
test('new studio can cast four roles and finish the purchased draft within starting resources',()=>{const [s,m]=fixture();const actors=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee);for(let role=0;role<4;role++){const p=actors[role];E.act(s,'audition',{id:m.id,person:p.id,role});const q=E.quote(s,p,m,role);E.act(s,'hire',{id:m.id,person:p.id,role,offer:q.high});}const dir=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:dir.id});E.act(s,'hire',{id:m.id,person:dir.id,offer:E.quote(s,dir,m).high});E.act(s,'greenlight',{id:m.id,sets:400,crew:600,effects:250,duration:8});for(let i=0;i<14&&m.stage!=='ready';i++){if(m.event)E.act(s,'event',{id:m.id,choice:'pay'});s.notices=[];E.act(s,'next');}assert.equal(m.stage,'ready');assert(s.cash>0);assert.equal(m.performances.length,4);assert(Number.isFinite(m.quality));assert.deepEqual(m.narrative,N.originalDraft());m.performances=[60,91,72,70];assert.equal(E.candidate(s,m,'Supporting Acting').person,m.contracts[1].id);});

test('unfunded story ambition changes finished quality without changing actors or reception biases',()=>{const [s,m]=fixture();const actors=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee);for(let role=0;role<4;role++){const p=actors[role];E.act(s,'audition',{id:m.id,person:p.id,role});E.act(s,'hire',{id:m.id,person:p.id,role,offer:E.quote(s,p,m,role).high});}const p=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:p.id});E.act(s,'hire',{id:m.id,person:p.id,offer:E.quote(s,p,m).high});const ambitious=structuredClone(s),film=ambitious.movies[0];film.narrative.beats=['signal','orbit','improvise','world','sacrifice','kill'];for(const state of [s,ambitious]){const f=state.movies[0];E.act(state,'greenlight',{id:f.id,sets:400,crew:600,effects:0,duration:8});for(let i=0;i<14&&f.stage!=='ready';i++){if(f.event)E.act(state,'event',{id:f.id,choice:'pay'});state.notices=[];E.act(state,'next');}}assert.equal(m.quality-film.quality,5.5);assert.deepEqual(m.performances,film.performances);assert.equal(m.criticBias,film.criticBias);});
