import test from 'node:test';import assert from 'node:assert/strict';import * as E from '../engine.js';import * as P from '../personality.js';
function cast(s,m,lead){const actors=s.people.filter(p=>p.kind==='actor'&&p.id!==lead.id).sort((a,b)=>a.fee-b.fee);for(let role=0;role<m.roles.length;role++){const p=role===0?lead:actors[role-1];E.act(s,'audition',{id:m.id,person:p.id,role});E.act(s,'hire',{id:m.id,person:p.id,role,offer:E.quote(s,p,m,role).high});}const d=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:d.id});E.act(s,'hire',{id:m.id,person:d.id,offer:E.quote(s,d,m).high});return d;}
function fixture(){const s=E.newGame(7),lead=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'actorPromise',{person:lead.id});const genre=lead.personality.goal;E.act(s,'original',{title:'Second Chances',genre,subgenre:E.GENRES[genre][0],scale:'Small'});const m=s.movies[0];for(let i=0;i<3;i++){s.notices=[];E.act(s,'next');}const d=cast(s,m,lead);return {s,m,lead,d};}
function greenlight(s,m){E.act(s,'greenlight',{id:m.id,sets:300,crew:350,effects:200,duration:8});}
function release(s,m){for(let i=0;i<25&&m.stage!=='ready';i++){if(m.event)E.act(s,'event',{id:m.id,choice:'pay'});s.notices=[];E.act(s,'next');}assert.equal(m.stage,'ready');E.act(s,'setRelease',{id:m.id,release:s.week+1});E.act(s,'confirmMarketing',{id:m.id,none:true});E.act(s,'distribute',{id:m.id,deal:'secure'});s.notices=[];E.act(s,'next');assert.equal(m.stage,'theaters');}
test('personality migration is deterministic, idempotent and leaves money, RNG and signed films unchanged',()=>{const {s,m}=fixture();const movies=JSON.stringify(s.movies),cash=s.cash,rng=s.rng;for(const p of s.people)delete p.personality;P.ensure(s);const saved=JSON.stringify(s);P.ensure(s);assert.equal(JSON.stringify(s),saved);assert.equal(JSON.stringify(s.movies),movies);assert.equal(s.cash,cash);assert.equal(s.rng,rng);assert.deepEqual(E.migrateSave(JSON.parse(saved)).people[0].personality,s.people[0].personality);});
test('promises reject duplicates, expire once, and cancellation is remembered once',()=>{const {s,m,lead}=fixture(),before=JSON.stringify(s);assert.throws(()=>E.act(s,'actorPromise',{person:lead.id}));assert.equal(JSON.stringify(s),before);s.week=lead.personality.promise.due+1;P.tick(s,()=>{});assert.equal(lead.personality.rapport,-6);P.tick(s,()=>{});assert.equal(lead.personality.rapport,-6);E.act(s,'actorPromise',{person:lead.id});greenlight(s,m);E.act(s,'cancel',{id:m.id});P.tick(s,()=>{});assert.equal(lead.personality.rapport,-10);assert.equal(lead.personality.promise,null);});
test('director style locks at filming, replacement resets approach, neutral retains zero modifiers',()=>{const {s,m,d}=fixture();E.act(s,'directorApproach',{id:m.id,choice:'back'});const plan=structuredClone(s);greenlight(s,m);assert.equal(m.peopleStory.backed,true);assert.deepEqual(P.adjustments(m),P.style(d));assert.throws(()=>E.act(s,'directorApproach',{id:m.id,choice:'balanced'}));const n=plan.movies[0];n.directorApproach.person='old-director';greenlight(plan,n);assert.equal(n.peopleStory.backed,false);assert.deepEqual(P.adjustments(n),{acting:0,story:0,direction:0,craft:0});});
test('real release fulfills ambition, changes next ambition, and creates one grounded fan follow-up',()=>{const {s,m,lead}=fixture(),genre=lead.personality.goal;E.act(s,'directorApproach',{id:m.id,choice:'back'});greenlight(s,m);assert.equal(lead.personality.promise.movie,m.id);release(s,m);assert.equal(lead.personality.promise,null);assert.equal(lead.personality.rapport,8);assert.notEqual(lead.personality.goal,genre);assert(lead.personality.memories.some(x=>x.text.includes(m.title)));const before=JSON.stringify(s);P.release(s,m,()=>{});assert.equal(JSON.stringify(s),before);for(let i=0;i<2;i++){s.notices=[];E.act(s,'next');}assert(m.fanCommunity.ready);assert(m.fanCommunity.text.includes(lead.name));assert(m.fanCommunity.text.includes(genre));assert.deepEqual(E.migrateSave(JSON.parse(JSON.stringify(s))).movies[0].fanCommunity,m.fanCommunity);});
test('fan spotlight is optional, atomic, charged to film and limited to four future weeks',()=>{const {s,m}=fixture();greenlight(s,m);release(s,m);s.week+=2;P.tick(s,()=>{});const cash=s.cash,spent=m.spent;E.act(s,'fanResponse',{id:m.id,choice:'spotlight'});assert.equal(s.cash,cash-25);assert.equal(m.spent,spent+25);assert.equal(P.demand(m,s.week),1);assert.equal(P.demand(m,s.week+1),1.08);assert.equal(P.demand(m,s.week+4),1.08);assert.equal(P.demand(m,s.week+5),1);const before=JSON.stringify(s);assert.throws(()=>E.act(s,'fanResponse',{id:m.id,choice:'thanks'}));assert.equal(JSON.stringify(s),before);});
test('unaffordable, invalid and ended-run spotlights do not change state; thanks builds rapport without spending',()=>{const {s,m,lead}=fixture();greenlight(s,m);release(s,m);s.week+=2;P.tick(s,()=>{});s.cash=10;let before=JSON.stringify(s);assert.throws(()=>E.act(s,'fanResponse',{id:m.id,choice:'spotlight'}));assert.equal(JSON.stringify(s),before);assert.throws(()=>E.act(s,'fanResponse',{id:m.id,choice:'bogus'}));assert.equal(JSON.stringify(s),before);m.stage='catalog';assert.throws(()=>E.act(s,'fanResponse',{id:m.id,choice:'spotlight'}));const trust=lead.personality.rapport;E.act(s,'fanResponse',{id:m.id,choice:'thanks'});assert.equal(s.cash,10);assert.equal(lead.personality.rapport,trust+2);});
test('legacy finished movies get no retroactive story events and sequels get clean snapshots',()=>{const {s,m}=fixture();greenlight(s,m);release(s,m);E.act(s,'sequel',{id:m.id});const sequel=s.movies[1];assert.equal(sequel.peopleStory,undefined);assert.equal(sequel.fanCommunity,undefined);delete m.peopleStory;delete m.fanCommunity;const before=JSON.stringify(m);P.release(s,m,()=>{});P.tick(s,()=>{});assert.equal(JSON.stringify(m),before);});
test('support and director tradeoffs change delivered work using the same simulation seed',()=>{const {s,m,d,lead}=fixture();const neutral=structuredClone(s),n=neutral.movies[0];neutral.people.find(p=>p.id===lead.id).personality.promise=null;E.act(s,'directorApproach',{id:m.id,choice:'back'});greenlight(s,m);greenlight(neutral,n);release(s,m);release(neutral,n);const style=P.style(d);assert.equal(m.performances[0],E.clamp(n.performances[0]+style.acting+4));assert.equal(m.performances[1],E.clamp(n.performances[1]+style.acting));assert.equal(m.directorPerformance,E.clamp(n.directorPerformance+style.direction));assert.equal(m.craft,E.clamp(n.craft+style.craft));assert.equal(m.storyExecution,E.clamp(n.storyExecution+style.story));});
test('fan lead follows role order even when the supporting actor was hired first',()=>{const {s,m,lead}=fixture();m.contracts.reverse();greenlight(s,m);assert.equal(m.peopleStory.actors[0].id,lead.id);});
