import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../engine.js';
import * as SF from '../scifi.js';
const cards=()=>Object.fromEntries(SF.SECTIONS.map(x=>[x.id,[x.cards[0]]]));
function create(){const s=E.newGame(7);E.act(s,'original',{title:'Silent Orbit',genre:'Sci-fi',subgenre:E.GENRES['Sci-fi'][0],scale:'Small',scifiCards:cards()});return [s,s.movies[0]];}
test('card validation rejects missing, foreign, duplicate and excess choices atomically',()=>{for(const change of [d=>d.setting=[],d=>d.setting=['Earth','Earth'],d=>d.setting=['Earth','Colony','Deep Space'],d=>d.setting=['Not a card'],d=>delete d.tone]){const s=E.newGame(7),before=JSON.stringify(s),d=cards();change(d);assert.throws(()=>E.act(s,'original',{title:'Bad',genre:'Sci-fi',subgenre:E.GENRES['Sci-fi'][0],scale:'Small',scifiCards:d}));assert.equal(JSON.stringify(s),before);}});
test('cards persist, revisions charge once, lock at filming and reject old rewrite path',()=>{const [s,m]=create();m.stage='packaging';const d=cards();d.tone=['Humorous','Dark'];const cash=s.cash,spent=m.spent;E.act(s,'scifiRewrite',{id:m.id,cards:d});assert.equal(s.cash,cash-50);assert.equal(m.spent,spent+50);E.act(s,'scifiRewrite',{id:m.id,cards:d});assert.equal(s.cash,cash-50);assert.deepEqual(E.migrateSave(JSON.parse(JSON.stringify(s))).movies[0].scifiCards,d);assert.throws(()=>E.act(s,'storyRewrite',{id:m.id,restore:true}));m.stage='filming';assert.throws(()=>E.act(s,'scifiRewrite',{id:m.id,cards:cards()}));});
test('execution drives reception; primary order matters; more cards do not guarantee higher scores',()=>{const m={scifiCards:cards(),scriptQuality:90,performances:[35,45],directorPerformance:55,craft:80,quality:66};const r=SF.evaluate(m);assert(r.groups.find(g=>g.name.startsWith('Idea')).score>r.groups.find(g=>g.name.startsWith('Character')).score);assert.equal(r.fans,Math.round(r.groups.reduce((n,g)=>n+g.score*g.share,0)));assert.deepEqual(SF.evaluate(m),r);const d=cards();d.tone=['Thoughtful','Humorous'];const a=SF.evaluate({...m,scifiCards:d});d.tone.reverse();const b=SF.evaluate({...m,scifiCards:d});assert.notDeepEqual(a.groups.map(g=>g.share),b.groups.map(g=>g.share));const uniform={...m,scriptQuality:70,performances:[70,70],directorPerformance:70,craft:70,quality:70};assert.equal(SF.evaluate(uniform).fans,70);const full=Object.fromEntries(SF.SECTIONS.map(x=>[x.id,x.cards.slice(0,2)]));assert.equal(SF.evaluate({...uniform,scifiCards:full}).fans,70);});
test('full card film lifecycle, real reception, stable report and fresh sequel results',()=>{const [s,m]=create();for(let i=0;i<3;i++){s.notices=[];E.act(s,'next');}assert.equal(m.stage,'packaging');const actors=s.people.filter(p=>p.kind==='actor').sort((a,b)=>a.fee-b.fee);for(let role=0;role<m.roles.length;role++){const p=actors[role];E.act(s,'audition',{id:m.id,person:p.id,role});E.act(s,'hire',{id:m.id,person:p.id,role,offer:E.quote(s,p,m,role).high});}const p=s.people.filter(p=>p.kind==='director').sort((a,b)=>a.fee-b.fee)[0];E.act(s,'audition',{id:m.id,person:p.id});E.act(s,'hire',{id:m.id,person:p.id,offer:E.quote(s,p,m).high});E.act(s,'greenlight',{id:m.id,sets:300,crew:350,effects:200,duration:8});for(let i=0;i<25&&m.stage!=='ready';i++){if(m.event)E.act(s,'event',{id:m.id,choice:'pay'});s.notices=[];E.act(s,'next');}assert.equal(m.stage,'ready');assert(m.scifiReception);assert.equal(m.fans,m.scifiReception.fans);assert.equal(m.critics,m.scifiReception.critics);E.act(s,'setRelease',{id:m.id,release:s.week+1});E.act(s,'confirmMarketing',{id:m.id,none:true});E.act(s,'distribute',{id:m.id,deal:'secure'});s.notices=[];E.act(s,'next');assert.equal(m.stage,'theaters');assert(m.gross>0);assert.deepEqual(E.migrateSave(JSON.parse(JSON.stringify(s))).movies[0].scifiReception,m.scifiReception);const before=JSON.stringify(s);E.criticReviews(m);assert.equal(JSON.stringify(s),before);E.act(s,'sequel',{id:m.id});assert.deepEqual(s.movies[1].scifiCards,m.scifiCards);assert.equal(s.movies[1].scifiReception,undefined);});
